### ISSUE TITLE
running 0.0.8 encrypted data is empty

### ISSUE THREAD

**Issue by junkloader52** [p1ratrulezzz/brainser#16]
I get the error `panic: encrypted data is empty`

I downloaded the resource.zip and extracted the key files.

Are there other resources I need?  It appears to be looking for agent.jar.enc

```
This tool is provided specially for Typical Society forum and shipped AS IS.
This tool is open source and can be used by anyone. 
Please note, this tool is only for demonstrating and non commercial use, 
if you love some software - buy it and use freely.

Visit: https://forum.losper.net/

Press 'Enter' to continue...
1. Patch (default flow)
2. Smart (but not clever) patch everything that is running
3. Exit
4. Cleanup mode: : On
0. Show info
2
Attention! Working in cleanup mode. This will not actually patch anything, just cleanup other agents! Disable cleanup mode to patch
Run all products that you want to patch and press enter...

Searching for products...
Found 1 products
Will patch these products:
GoLand(/home/<user>/.config/JetBrains/GoLand2023.1/goland64.vmoptions)
Press enter to continue...

panic: encrypted data is empty

goroutine 1 [running]:
jetbrainser/src/cryptor.Decrypt({0x0, 0x0, 0x0})
        /home/<user>/Documents/brainser/src/cryptor/crypt.go:32 +0x111
main.getResource({0x572360?, 0x9?})
        /home/<user>/Documents/brainser/src/app/helpers.go:59 +0xad
main.checkAgentExists({0x0, 0x0, 0x5a6de0?})
        /home/<user>/Documents/brainser/src/app/helpers.go:126 +0x33
main.doPatch({0xc00034b5a3, 0x3d}, {0xc000239a70, 0x2a}, {0x0, 0x0}, 0x1)
        /home/<user>/Documents/brainser/src/app/patch.go:48 +0x392
main.doAutoPatch({0xc0001a51a0?, 0xc0001a2008?}, {0xc0001ac1b0?, 0x1, 0x1?})
        /home/<user>/Documents/brainser/src/app/item_patch_smart.go:54 +0x2f6
main.item_patch_procs()
        /home/<user>/Documents/brainser/src/app/item_patch_smart.go:37 +0x4e8
main.menu_loop.func2(0x547e60?, {0xc0001aa0f8, 0x5, 0x0?})
        /home/<user>/Documents/brainser/src/app/menuloop.go:68 +0x1ca
main.menu_loop()
        /home/<user>/Documents/brainser/src/app/menuloop.go:83 +0x305
main.main()
        /home/<user>/Documents/brainser/src/app/app.go:6 +0x17
<user>@1AK0050UK:~/Documents/brainser$ 
```

**Comment by p1ratrulezzz** [comment]
Contents of the zip must be put under the directory

src/app/resources_enc
i.e: src/app/resources_enc/something.txt.enc

**Comment by junkloader52** [comment]
The resources I have contain key files resources/*.key so I must have the wrong ones.

I found them from your post on losper https://losper.net/topic/283-activation-instruction-jetbrains/?do=findComment&comment=979

Can you put the correct files or explain how these need modifying please?

**Comment by p1ratrulezzz** [comment]
I've added new resources file, download it from the same topic on the forum
and put under src/app/ so it will be src/app/resources_enc

пн, 8 мая 2023 г. в 14:11, junkloader52 ***@***.***>:
