### ISSUE TITLE
Patch won't work with 2022.1-2022.1.2

### ISSUE THREAD

**Issue by Zly-u** [p1ratrulezzz/brainser#3]
Somewhere was said that it worked for 1.1, but didn't worked for me.
Here's a log:

```
panic: runtime error: slice bounds out of range [-1:]

goroutine 1 [running]:
main.cleanupVmoptions({0xc000094000?, 0x0?, 0x135b080?})
        S:/Trash/go/brainser/src/app/helpers.go:80 +0x385
main.doPatch({0xc000016550, 0x4b}, {0xc000010300?, 0x32?}, 0x7)
        S:/Trash/go/brainser/src/app/patch.go:35 +0x259
main.item_patch_procs()
        S:/Trash/go/brainser/src/app/item_patch_smart.go:42 +0x685
main.menu_loop.func2({0xc0000aa350, 0x4, 0x8?}, 0x0?)
        S:/Trash/go/brainser/src/app/menuloop.go:58 +0xa5
main.menu_loop()
        S:/Trash/go/brainser/src/app/menuloop.go:67 +0x2b7
main.main()
        S:/Trash/go/brainser/src/app/app.go:6 +0x17
```

**Comment by p1ratrulezzz** [comment]
Hello. Can you provide your vmoptions file?

**Comment by Zly-u** [comment]
Oh, your hint on vmoptions helped actually.
Found one in appdata that had busted structure in it or whatever, used an old kind of method, deleted it and the thing worked, thanks!.

Here's what was inside of it if you are curious, that's all it had:

```
-javaagent:C:\Users\Public\.jetbrains\jetbrains-agent-v3.2.0.0f1f.69e=[some sort of long hash/key]
```

**Comment by p1ratrulezzz** [comment]
yep, just remove this file then try again. But i've found the bug and fixed so thanks for reporting it
